Allow specifying mac on macvlan link creation
rust-netlink/rtnetlink pull request #45
Opened 2023-10-03 16:31 UTC by maiqueb

This probably should be added for other interface types, not only macvlan.

Welcome any feedback.

Fixes: #30

2023-10-03 16:33 UTC, maiqueb commented
I still need to figure out how to add unit tests to this.

2023-10-03 16:33 UTC, maiqueb commented on Cargo.toml
> +macaddr = "1.0"
not sure we want to consume this dependency.

2024-01-10 12:02 UTC, cathay4t requested changes

2024-01-10 12:02 UTC, cathay4t commented on Cargo.toml
> +macaddr = "1.0"
We should be cautious on introducing new dependency.

But in our case, this is dependency for example and test code, please add this dependency to `dev-dependencies` section of `Cargo.toml`.

2024-01-10 14:10 UTC, maiqueb commented on Cargo.toml
> +macaddr = "1.0"
Makes sense. 

As a follow up I can try to port (new implementation) the required functions into the project, thus removing the need for the dependency.

2024-01-12 01:07 UTC, cathay4t requested changes
CI failed.

I noticed we already have `LinkSetRequest::address()`. Can we introduce `LinkAddRequest::address()` to this PR. Otherwise this PR is purely for test and example code, does not make sense to have that PR title.

2024-01-12 09:38 UTC, maiqueb commented
> CI failed.

Hm, locally I was using stable rust, and the ` wrap_comments` knob is only available in the nightly channel; thus, it didn't have the same output as CI. It should be fixed now @cathay4t . 

> 
> I noticed we already have `LinkSetRequest::address()`. Can we introduce `LinkAddRequest::address()` to this PR. Otherwise this PR is purely for test and example code, does not make sense to have that PR title.

Done. I've chosen to slightly refactor the `name` function as well (re-using the `append_nla` method) since that uses less code (and code reuse is good). Finally, I've chosen to make it public (just like in `LinkSetRequest`) to be able to use a builder like pattern (i.e. `link_handle.add().macvlan(...).name(<name>).address(<mac>)`).

I think this is ready for another review round @cathay4t .

Thanks for the help / reviews.

2024-01-12 10:57 UTC, cathay4t approved these changes
LGTM. Thanks!

2024-01-12 10:57 UTC, merged