feat(ns): implement RAII network namespace guard
rust-netlink/rtnetlink pull request #5
Opened 2022-11-09 02:36 UTC by Ji-Xinyou

The guard can let the thread construcing the guard enter its own network namespace, and return to its old network namespace when the guard called Drop.

Signed-off-by: Ji-Xinyou <jerryji0414@outlook.com>

2022-11-10 18:36 UTC, Ji-Xinyou commented
PTAL, thanks @cathay4t @JohnTitor

2022-11-28 05:38 UTC, cathay4t commented
Hi @Ji-Xinyou,

Thanks for the patch!

This is NS guard is new to me. When I asking experts around, could you provide example or test case to demonstrate your patch is actually working as expected?

2022-11-28 06:03 UTC, Ji-Xinyou commented
> cathay4t

Thanks you for reminding me. I will follow up some unit tests to clarify its usage in a few days :)

2023-03-06 01:02 UTC, cathay4t requested changes
I failed to find any document mentioned about `RAII network namepsace guard` indicating it is not a well known name. From the code, I noticed you are try to do the same as `ip netns attach <NETNSNAME> <PID>`, if so, please change commit message somthing like `supporting attaching current thread to new network namespace`.

Meanwhile, a test case required, using `ip netns` to verify could be better.

2023-06-25 14:14 UTC, cathay4t commented
@Ji-Xinyou Any update?

2023-06-25 17:42 UTC, Ji-Xinyou commented
> @Ji-Xinyou Any update?

I am truly sorry for the last response on this PR, I am recently a little bit busy but I will try to update the test case as soon as possible.

2024-01-10 12:36 UTC, cathay4t commented
@Ji-Xinyou Any update?

2024-01-10 12:53 UTC, Ji-Xinyou commented
> @Ji-Xinyou Any update?

I wrote a test on one of my computers but I am not with that machine with me right now. I expect to submit that next week as soon as I head back to the US. Sorry about being late.

2024-01-14 21:03 UTC, Ji-Xinyou commented
Hi, I notice that the testcases need to be run as root since we need to manipulate the network namespace. Any workaround suggested?

2024-01-25 01:42 UTC, closed without merging