`netlink-*` packages re-exported
rust-netlink/rtnetlink pull request #66
Opened 2024-05-14 10:28 UTC by pseusys

Closes #28.
Re-exported `netlink-*` dependencies in `lib.rs` file to avoid dependency versioning hell while using package.
It seems like the original issue maintainer has abandoned it, so I decided to step in and fix this (as at least for now it seems to be super easy).
Let me know if there are anything else I could fix about this issue.

2024-05-30 01:53 UTC, cathay4t requested changes
In the old time, we are reexporting as `rtnetlink:packet` for `netlink_packet_route`.
So let's remove the prefix.

2024-05-30 08:27 UTC, cathay4t commented
Let's try:

```rust
pub use netlink_sys as sys;
pub use netlink_packet_utils as utils;
pub use netlink_packet_route as packet;
pub use netlink_packet_core as packet_core;
pub use netlink_proto as proto;
```

2024-05-30 08:28 UTC, cathay4t commented
Please squash these commits into single one.

2024-06-24 01:33 UTC, cathay4t commented
You made a good point in differ from original crate.

I would vote to your suggestion:

```rust
pub use netlink_sys as sys;
pub use netlink_packet_utils as packet_utils;
pub use netlink_packet_route as packet_route;
pub use netlink_packet_core as packet_core;
pub use netlink_proto as proto;
```

@little-dude @JohnTitor What's your options on this re-export?

2024-06-24 08:34 UTC, little-dude commented
Hello :) I don't have a strong opinion on this one. I agree on the fact that these re-exports would be nice to have, but I don't mind whether the original names are kept or not.

2024-06-26 13:16 UTC, little-dude commented
Hey @pseusys  thanks for your work.

Normally, it's quite easy to squash all the commits. Here is a demo.

Let's say I want to work on a new branch called `rebase-demo`, which starts from the tip of upstream's main branch:

```
❯ git remote -v                                                                                                                                                                                                    
origin  git@github.com:little-dude/rtnetlink.git (fetch)                                                 
origin  git@github.com:little-dude/rtnetlink.git (push)                                                  
upstream        git@github.com:rust-netlink/rtnetlink.git (fetch)                                        
upstream        git@github.com:rust-netlink/rtnetlink.git (push)  

❯ git fetch upstream main                                                                                
From github.com:rust-netlink/rtnetlink              
 * branch            main       -> FETCH_HEAD

❯ git checkout -b rebase-demo                                                                            
Switched to a new branch 'rebase-demo'                                                                   
                                  
❯ git reset --hard origin/main                                                                           
HEAD is now at 6d77e01 New release 0.14.1 
```

We work on the branch and make 3 commits:

```
❯ echo "hello a.txt" > a.txt && git add a.txt && git commit -m 'add a.txt file'

[rebase-demo b1c075b] add a.txt file
 1 file changed, 1 insertion(+)
 create mode 100644 a.txt

❯ echo "hello b.txt" > b.txt && git add b.txt && git commit -m 'add b.txt file'

[rebase-demo 98d0331] add b.txt file
 1 file changed, 1 insertion(+)
 create mode 100644 b.txt

❯ echo "more stuff into a.txt" >> a.txt && git add a.txt && git commit -m 'edit a.txt'
[rebase-demo d9ced67] edit a.txt
 1 file changed, 1 insertion(+)

❯ git log -n4 --oneline
d9ced67 (HEAD -> rebase-demo) edit a.txt
98d0331 add b.txt file
b1c075b add a.txt file
6d77e01 (tag: v0.14.1, origin/main, origin/flock, origin/HEAD, test, flock) New release 0.14.1
```

To squash all three commits we can rebase the branch interactively (with `-i`):

```
❯ git rebase -i origin/main
```

This opens a file in our default editor which looks like this:

```
pick b1c075b add a.txt file
pick 98d0331 add b.txt file
pick d9ced67 edit a.txt

# Rebase 6d77e01..d9ced67 onto 6d77e01 (3 commands)
#
# Commands:
# p, pick <commit> = use commit
# r, reword <commit> = use commit, but edit the commit message
# e, edit <commit> = use commit, but stop for amending
# s, squash <commit> = use commit, but meld into previous commit
# f, fixup [-C | -c] <commit> = like "squash" but keep only the previous
#                    commit's log message, unless -C is used, in which case
#                    keep only this commit's message; -c is same as -C but
#                    opens the editor
# x, exec <command> = run command (the rest of the line) using shell
# b, break = stop here (continue rebase later with 'git rebase --continue')
# d, drop <commit> = remove commit
# l, label <label> = label current HEAD with a name
# t, reset <label> = reset HEAD to a label
# m, merge [-C <commit> | -c <commit>] <label> [# <oneline>]
#         create a merge commit using the original merge commit's
#         message (or the oneline, if no original merge commit was
#         specified); use -c <commit> to reword the commit message
# u, update-ref <ref> = track a placeholder for the <ref> to be updated
#                       to this position in the new commits. The <ref> is
#                       updated at the end of the rebase
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
```

The comments explain that in order to squash commits we need to change the `pick` into a `squash` (or `s`). So we edit the file so that it looks like this (I'm not copying the comments again):

```
pick b1c075b add a.txt file
s 98d0331 add b.txt file
s d9ced67 edit a.txt
```
After saving and exiting, git starts the rebase and open our editor again so that we can choose a commit message for our squashed commit:

```
# This is a combination of 3 commits.
# This is the 1st commit message:

add a.txt file

# This is the commit message #2:

add b.txt file

# This is the commit message #3:

edit a.txt

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# Date:      Wed Jun 26 14:46:32 2024 +0200
#
# interactive rebase in progress; onto 6d77e01
# Last commands done (3 commands done):
#    squash 98d0331 add b.txt file
#    squash d9ced67 edit a.txt
# No commands remaining.
# You are currently rebasing branch 'rebase-demo' on '6d77e01'.
#
# Changes to be committed:
#	new file:   a.txt
#	new file:   b.txt
#
```

We edit the file such that we have a new commit message:

```
# This is a combination of 3 commits.
# This is the 1st commit message:

add a.txt and b.txt file

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# Date:      Wed Jun 26 14:44:16 2024 +0200
#
# interactive rebase in progress; onto 6d77e01
# Last commands done (3 commands done):
#    squash 8f15c6c add b.txt file
#    squash b8322df edit a.txt
# No commands remaining.
# You are currently rebasing branch 'rebase-demo' on '6d77e01'.
#
# Changes to be committed:
#	new file:   a.txt
#	new file:   b.txt
#
```

Save and exit the editor, and git finished the rebase. We now have a single squashed commit:

```
❯ git log -n2 --oneline
ebd6838 (HEAD -> rebase-demo) add a.txt and b.txt file
6d77e01 (tag: v0.14.1, origin/main, origin/flock, origin/HEAD, test, flock) New release 0.14.1
```

----------------

Now in your case it's more complicated than this because your branch contains a merge commit, which was likely introduce when you did a `git pull`:

```
❯ git log upstream/main..HEAD --oneline
33329b3 (HEAD -> netlink-packages-re-exporting) Merge branch 'main' into netlink-packages-re-exporting <--- this is a merge commit
0dcc06e all the branch commits squashed
05bd572 `netlink-*` packages re-exported
```

We don't want that commit in our project, the rebase I just showed won't be enough to remove it, because by default it ignores merge commits.

One easy brute-force solution is to:

- create a new branch: `git checkout -b tmp-branch`
- reset that branch to the tip of the upstream main branch: `git fetch upstream && git reset --hard upstream/main` (assuming your remote is called `upstream`)
- cherry pick the few commits we want: `git cherry-pick 05bd572 0dcc06e`
- squash the commits using `git rebase -i`
- now that `tmp-branch` looks like what we want, we go back to our "normal" branch and reset it to `tmp-branch`: `git checkout netlink-packages-re-exporting && git reset --hard tmp-branch`
- `git push origin netlink-packages-re-exporting --force`

Another solution is to do a `git rebase -i` with the `--rebase-merges` option. This is similar to a normal rebase but requires a bit more understanding of what's going on. 

```
git rebase -i -r origin/main
```

Git opens a file that looks like this (I cut out the comments):

```
label onto

@ Branch main
reset onto
pick de62338 Provide the ability to set the underlying link ID when adding xfrm link types
pick 6e4fabd Fix cargo clippy
pick 6863102 Implement add vrf link (issue #40)
pick 6896bae update to netlink-packet-route 0.20
label branch-point
pick b5e0cb6 add `RouteAddRequest<IpAddr>`
pick 24bf04f Move the `RouteAddRequest` method into a separate builder
pick 74a0302 add_neighbour example: set required link_local_address
pick 1baa307 Run cargo fmt
pick e0030d9 example: Fix help message of add_neighbour
la [...]

2024-06-29 02:58 UTC, cathay4t commented
I have amend PR:
 * `git fetch upstream; git rebase --interactive upstream/main`
 * Also add sign off line `Signed-off-by: pseusys <shveitsar215@gmail.com>` to commit message.
 * Used `cargo fmt` to sort the `pub use` in `src/lib.rs`.

2024-06-29 02:59 UTC, cathay4t approved these changes

2024-06-29 03:01 UTC, cathay4t commented
I guess the next step for this PR would be change all internal code and document to use `crate::packet_route::` instead of `netlink_packet_route::`

2024-06-29 03:01 UTC, merged