Support `ip route get`
rust-netlink/rtnetlink pull request #86
Opened 2024-11-26 13:58 UTC by hack3ric

Rework of https://github.com/rust-netlink/rtnetlink/pull/23. Only adds `RouteGetRequest::dump` option, where specifying `req.dump(false)` will mimic the behaviour of `ip route get`, and replacing `impl TryStream` with `impl Stream<Item = Result<...>>`. There is no breaking change.

2024-12-26 14:16 UTC, nhed commented
Any idea bout the status f this PR?   
I need `ip route get` functionality and hacked out the dump locally.

2024-12-26 14:24 UTC, hack3ric commented
Seems the maintainer has been inactive for some time on this repo, so we have to either wait or fork.

2024-12-26 16:14 UTC, nhed commented
not sure if valuable - but as an alternate to adding a dump variable at construction time I thought it might make sense to drive this behavior by the presence of a destination attribute.

If destination attribute was added (as one would have to to obtain a route) user is looking for a single route
otherwise - dump all the routes


```
diff --git a/src/route/get.rs b/src/route/get.rs
index a938532..68f27bf 100644
--- a/src/route/get.rs
+++ b/src/route/get.rs
@@ -11,7 +11,7 @@ use netlink_packet_route::{
     route::RouteMessage, AddressFamily, RouteNetlinkMessage,
 };
 
-use crate::{try_rtnl, Error, Handle};
+use crate::{try_rtnl, Error, Handle, packet_route::route::RouteAttribute};
 
 pub struct RouteGetRequest {
     handle: Handle,
@@ -51,9 +51,14 @@ impl RouteGetRequest {
             message,
         } = self;
 
+        let has_dest = message.attributes.iter().any(|attr| match attr {
+            RouteAttribute::Destination(_) => true,
+            _ => false,
+        });
+
         let mut req =
             NetlinkMessage::from(RouteNetlinkMessage::GetRoute(message));
-        req.header.flags = NLM_F_REQUEST | NLM_F_DUMP;
+        req.header.flags = NLM_F_REQUEST | if has_dest { 0 } else { NLM_F_DUMP };
 
         match handle.request(req) {
             Ok(response) => Either::Left(response.map(move |msg| {
```

2024-12-27 03:16 UTC, nhed commented
My rust is not so great - so I wasn't able to use your fix - so you have an example of how you would modify the existing examples?  Reading your commit message I tried this but `dump` is just a field, not an access method.

```
+++ b/examples/get_route.rs
@@ -35,7 +35,7 @@ async fn dump_addresses(
         IpVersion::V4 => RouteMessageBuilder::<Ipv4Addr>::new().build(),
         IpVersion::V6 => RouteMessageBuilder::<Ipv6Addr>::new().build(),
     };
-    let mut routes = handle.route().get(route).execute();
+    let mut routes = handle.route().get(route).dump(false).execute();
     while let Some(route) = routes.try_next().await? {
         println!("{route:?}");
     }
```

Feels like one would need to add an access method,  might just make my own temporary for till that clears up as the solution I outlined in the prior comment works transparently

2024-12-27 05:48 UTC, hack3ric commented
Oops, seems like I somehow missed `.dump()` method when cherry-picking from my own branch. Fixed now. Thanks for the review!

> If destination attribute was added (as one would have to to obtain a route) user is looking for a single route otherwise - dump all the routes

This definitely seems feasible! I wonder if there are corner cases, though. I will integrate your changes and mention you in the commit message when I am less busy (or create a new PR superseding this one) :)

2024-12-27 19:48 UTC, nhed commented
> I will integrate your changes

if you do please note i updated my comment with slightly cleaner code

2025-01-21 01:17 UTC, cathay4t requested changes
For the `get` support, the code is OK.

For changing `TryStream` to `Stream`, I don't like breaking API  with a commit holding zero reasoning comment. Breaking commonly used API require all users to change their code, please prove we have good benefit for this breakage.

2025-01-21 01:17 UTC, cathay4t commented
Sorry for the late review. Please check above comment.

2025-01-25 17:00 UTC, hack3ric commented
> For changing `TryStream` to `Stream`, I don't link breaking API with a commit holding zero reasoning comment. Breaking commonly used API require all users to change their code, please prove we have good benefit for this breakage.

The problem with `impl TryStream` is that the opaque type cannot be used as `Stream` (thus `StreamExt`) anymore, only `TryStream`, because types implementing the latter does not necessarily implement the former. This also causes problems with dynamic dispatch, as shown in [Rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=62a413343c764b6df237332717b665bd) and https://github.com/rust-netlink/rtnetlink/pull/23. By making this change we can use methods from both traits and should not break users' current usage.

2025-05-07 14:17 UTC, hack3ric commented
@cathay4t Hi, is there anything else to work on this PR? I've rebased the `TryStream` commit with justifications.

2025-08-21 09:54 UTC, cathay4t approved these changes

2025-08-21 09:55 UTC, merged